CREATE TABLE `persone` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Nome` varchar(50) DEFAULT NULL,
  `Cognome` varchar(75) DEFAULT NULL,
  `Indirizzo` text,
  `Citta` varchar(100) DEFAULT NULL,
  `Provincia` varchar(10) DEFAULT NULL,
  `Nazione` varchar(50) DEFAULT NULL,
  `CAP` varchar(5) DEFAULT NULL,
  `TelefonoDomicilio` varchar(50) DEFAULT NULL,
  `TelefonoUfficio` varchar(50) DEFAULT NULL,
  `DataDiNascita` date DEFAULT NULL,
  `UltimoContatto` datetime DEFAULT NULL,
  `Nota` longtext,
  `Titolo` varchar(50) DEFAULT NULL,
  `Carica` varchar(100) DEFAULT NULL,
  `Societa` varchar(255) DEFAULT NULL,
  `SitoWeb` varchar(255) DEFAULT NULL,
  `ModificatoDa` varchar(50) DEFAULT NULL,
  `EMail` varchar(150) DEFAULT NULL,
  `Fax` varchar(50) DEFAULT NULL,
  `Cellulare` varchar(50) DEFAULT NULL,
  `IM` varchar(150) DEFAULT NULL,
  `Categorie` varchar(255) DEFAULT NULL,
  `DisplayName` varchar(255) DEFAULT NULL,
  `piva` varchar(20) DEFAULT NULL,
  `cf` varchar(16) DEFAULT NULL,
  `modified` datetime NOT NULL,
  `created` datetime NOT NULL,
  `iban` varchar(30) DEFAULT NULL,
  `NomeBanca` varchar(50) DEFAULT NULL,
  `altroIndirizzo` text,
  `altraCitta` varchar(50) DEFAULT NULL,
  `altroCap` varchar(5) DEFAULT NULL,
  `altraProv` varchar(2) DEFAULT NULL,
  `altraNazione` varchar(2) DEFAULT NULL,
  `EntePubblico` tinyint(1) DEFAULT NULL,
  `codiceIPA` varchar(255) DEFAULT NULL,
  `indirizzoPEC` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Cognome` (`Cognome`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;


-- 2021-01-26 14:48:50
