CREATE TABLE `persone` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Nome` varchar(50) DEFAULT NULL,
  `Cognome` varchar(75) DEFAULT NULL,
  `Indirizzo` text,
  `Citta` varchar(100) DEFAULT NULL,
  `Provincia` varchar(10) DEFAULT NULL,
  `Nazione` varchar(50) DEFAULT NULL,
  `CAP` varchar(5) DEFAULT NULL,
  `TelefonoDomicilio` varchar(50) DEFAULT NULL,
  `TelefonoUfficio` varchar(50) DEFAULT NULL,
  `DataDiNascita` date DEFAULT NULL,
  `LuogoDiNascita` varchar(255) DEFAULT NULL,
  `UltimoContatto` datetime DEFAULT NULL,
  `Nota` text,
  `Titolo` varchar(50) DEFAULT NULL,
  `Carica` varchar(100) DEFAULT NULL,
  `Societa` varchar(255) DEFAULT NULL,
  `SitoWeb` varchar(255) DEFAULT NULL,
  `ModificatoDa` varchar(50) DEFAULT NULL,
  `EMail` varchar(150) DEFAULT NULL,
  `Fax` varchar(50) DEFAULT NULL,
  `Cellulare` varchar(50) DEFAULT NULL,
  `IM` varchar(150) DEFAULT NULL,
  `Categorie` varchar(255) DEFAULT NULL,
  `DisplayName` varchar(255) DEFAULT NULL,
  `piva` varchar(20) DEFAULT NULL,
  `cf` varchar(16) DEFAULT NULL,
  `modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `iban` varchar(30) DEFAULT NULL,
  `NomeBanca` varchar(50) DEFAULT NULL,
  `altroIndirizzo` text,
  `altraCitta` varchar(50) DEFAULT NULL,
  `altroCap` varchar(5) DEFAULT NULL,
  `altraProv` varchar(2) DEFAULT NULL,
  `altraNazione` varchar(2) DEFAULT NULL,
  `EntePubblico` tinyint(1) DEFAULT NULL,
  `codiceIPA` varchar(255) DEFAULT NULL,
  `azienda_id` int DEFAULT NULL,
  `mailchimp_hash` text,
  `PecEmail` varchar(255) DEFAULT NULL,
  `accetta_trattamento_dati` tinyint(1) NOT NULL DEFAULT '0',
  `clausole_vessatorie` tinyint(1) NOT NULL DEFAULT '0',
  `accetta_contratto_partner` tinyint(1) DEFAULT NULL,
  `accetta_newsletter` tinyint(1) DEFAULT NULL,
  `ip_optin` varchar(45) DEFAULT NULL,
  `date_optin` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Cognome` (`Cognome`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;